CREATE DATABASE IF NOT EXISTS battlefield6 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
USE battlefield6;

CREATE TABLE IF NOT EXISTS players (
  ea_id BIGINT PRIMARY KEY,
  handle VARCHAR(64) NOT NULL,
  platform VARCHAR(12) NULL,               -- cached for refresh calls to Tracker
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  deaths INT UNSIGNED NOT NULL DEFAULT 0,
  wins INT UNSIGNED NOT NULL DEFAULT 0,
  losses INT UNSIGNED NOT NULL DEFAULT 0,
  score INT UNSIGNED NOT NULL DEFAULT 0,
  last_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

